# Generated by Django 3.2 on 2023-01-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_user_confirmation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='review',
            new_name='review_id',
        ),
    ]
