# Generated by Django 3.2 on 2023-01-26 05:33

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20230126_0732'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='one_review_one_author',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='username_default', max_length=32, unique=True, validators=[api.utils.username_validation]),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('title', 'author')},
        ),
    ]
