# Generated by Django 3.2 on 2023-01-26 07:00

from django.db import migrations, models
import reviews.utils


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20230126_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[reviews.utils.year_validate]),
        ),
    ]
