# Generated by Django 3.2 on 2023-02-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_alter_review_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
